#baseURL = "https://d-v-dlee-blog.onrender.com/"
baseURL = "https://dvdlee.me"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Website of David Lee"
theme = "anatole"
summarylength = 10
enableEmoji = true
#SameSite = None

# Enable Disqus
#disqusShortname = ""

# Google Analytics
googleAnalytics = "UA-172988296-1"

[params]
title = "dvdlee"
author = "David Lee"
description = "Futbol lover. Cast iron apprentice. Outdoor enthusiast."
profilePicture = "images/solo3.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["post"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/d-v-dlee/"

[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/d-v-dlee"

[[params.socialIcons]]
icon = "fa-instagram"
title = "instagram"
url = "https://www.instagram.com/d_v_dlee/"

[[params.socialIcons]]
icon = "fa-envelope"
title = "e-mail"
url = "mailto:davidlee327@gmail.com"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"